import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/Providers/Theme-Provider";
import { ParallaxProviders } from "@/Providers/Parallax-Provider";
import { Saira } from 'next/font/google';

const saira = Saira({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'], // choose the weights you need
  style: ['normal', 'italic'], // for italics
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${saira.className} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ParallaxProviders>
            
              {children}
            
          </ParallaxProviders>
        </ThemeProvider>
      </body>
    </html>
  );
}
